### ISSUE TITLE
ValueDump errors when running

### ISSUE THREAD

**Issue by ixiblat** [ISeeDEDPpl/Questor#107]
The following errors occurs when running ValueDump from Experimental with the update from 2012-06-05 6:10 GMT.  This was using both the compile batch file and compiling on my own using VS2010.

[ValueDump] Loading hangar items
Exception during event execution: System.NullReferenceException: Object reference not set to an instance of an object.
   at Questor.Modules.Caching.ItemCache.get_TypeId()
   at Questor.Modules.Caching.ItemCache.get_InvType()
   at QuestorManager.Actions.ValueDump.<ProcessState>b__c(ItemCache i)
   at System.Linq.Enumerable.WhereListIterator`1.MoveNext()
   at System.Collections.Generic.List`1.InsertRange(Int32 index, IEnumerable`1 collection)
   at System.Collections.Generic.List`1.AddRange(IEnumerable`1 collection)
   at QuestorManager.Actions.ValueDump.ProcessState()
   at QuestorManager.QuestorManagerUI.OnFrame(Object sender, EventArgs e)
   at ..(DirectEve , Object , LSEventArgs )
   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

**Comment by ixiblat** [comment]
Those errors were using the ValueDump from the QuestorManager side.  I should have used ValueDump itself to check but was tired and did not; I have now, and it is working fine.  Very sorry for the bug report without appropriate testing first.
