### ISSUE TITLE
Exception during event execution, not shown in the logs

### ISSUE THREAD

**Issue by xelj** [ISeeDEDPpl/Questor#150]
Every time after undocking, not shown in the logs, can only be viewed in the console

Exception during event execution: System.NullReferenceException: Object reference not set to an instance of an object.
   at Questor.Modules.BackgroundTasks.Cleanup.ProcessState()
   at Questor.Questor.OnframeProcessEveryPulse()
   at Questor.Questor.OnFrame(Object sender, EventArgs e)
   at ..(DirectEve , Object , LSEventArgs )
   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

**Comment by ISeeDEDPpl** [comment]
This should be fixed in current experimental. It was an issue with Directeve and listing windows while in a session change. We work around it by not trying to list windows while in a session change. 

These exceptions are more useful if you have the *.pdb files in .net programs as well so that the exceptions would show line numbers.

**Comment by xelj** [comment]
In just downloaded build of all the same.

Exception during event execution: System.NullReferenceException: Object reference not set to an instance of an object.
   at Questor.Modules.Logging.Statistics.WriteDroneStatsLog() in C:\Users\xelj\Desktop\ISeeD1907\Questor.Modules\Logging\Statistics.cs:line 221
   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in C:\Users\xelj\Desktop\ISeeD1907\Questor\Behaviors\CombatMissionsBehavior.cs:line
895
   at Questor.Questor.OnFrame(Object sender, EventArgs e) in C:\Users\xelj\Desktop\ISeeD1907\Questor\Questor.cs:line 511
   at ..(DirectEve , Object , LSEventArgs )
   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

Exception during event execution: System.NullReferenceException: Object reference not set to an instance of an object.
   at Questor.Modules.BackgroundTasks.Cleanup.ProcessState() in C:\Users\xelj\Desktop\ISeeD1907\Questor.Modules\BackgroundTasks\Cleanup.cs:line 530
   at Questor.Questor.OnframeProcessEveryPulse() in C:\Users\xelj\Desktop\ISeeD1907\Questor\Questor.cs:line 391
   at Questor.Questor.OnFrame(Object sender, EventArgs e) in C:\Users\xelj\Desktop\ISeeD1907\Questor\Questor.cs:line 435
   at ..(DirectEve , Object , LSEventArgs )
   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

First fixed setting  DroneStatsLog to false
Second -- removing commit https://github.com/ISeeDEDPpl/Questor/commit/916d7e7927db9485d02600fcf563cf49bcdce4fa

**Comment by ISeeDEDPpl** [comment]
The 1st issue is created because you likely do not have your 
`
<transportShipName>NameOfMyHaulingShipForCouriers</transportShipName> 
`
defined in your character XML

the 2nd issue I fixed in current experimental. Cleanup should not have been trying to list windows when we were in a session change.

**Comment by xelj** [comment]
No, I have transportShipName in charname.xml

**Comment by ISeeDEDPpl** [comment]
This should now be resolved. if you see any exceptions now please open another issue.
