### ISSUE TITLE
Current build wont undock

### ISSUE THREAD

**Issue by I3Questor** [ISeeDEDPpl/Questor#173]
Hi,

Current build (ISeeDEDPpl-Questor-7ffcdaa) wont undock or bring up the questor console.

Thanks for all your hard work mate.

**Comment by ISeeDEDPpl** [comment]
I just re-tested with binaries produced by current-github:
https://github.com/ISeeDEDPpl/Questor/commits/experimental
or: https://github.com/ISeeDEDPpl/Questor/zipball/experimental
and found no problems.

If questor is not undocking you can enable 
`
<debugAutostart>true</debugAutostart>
<debugIdle>true</debugIdle> 
`
in your characters settings xml and send me the logs. 

the fact that you aren't able to pull up the innerspace console indicates you are having an innerspace issue through, not a questor one. Questor relies on DirectEVE, DirectEVE relies on Innerspace (and so does questor to a degree). If innerspoace is not working correctly on your PC DirectEVE and Questor have no hope. 

edit: ahhh he said "questor console" not "innerspace console"

**Comment by I3Questor** [comment]
This is what i get.

Unhandled exception in application.
Outer Exception: System.ArgumentException: An item with the same key has already been added.

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)

   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)

   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)

   at Questor.Storylines.Storyline..ctor()

   at Questor.Behaviors.CombatMissionsBehavior..ctor()

   at Questor.Questor..ctor(QuestorfrmMain form1)

   at Questor.QuestorfrmMain..ctor()

   at Questor.Program.Main(String[] args)

   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)

   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, Evidence assemblySecurity, String[] args)

   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, Evidence assemblySecurity, String[] args)

   at LavishVMRuntime.LVMDomainManager.AsEx.NewExecuteAssembly4()

   at LavishVMRuntime.LVMDomainManager.AsEx.NewExecuteAssembly()

   at LavishVMRuntime.LVMDomainManager.AssemblyExecuter(Object Obj)

**Comment by ISeeDEDPpl** [comment]
ok, now try that again with the *.pdb files in the /net programs directory also so that we get line numbers. 

if you can use the #transfertolive#.bat it copies not only the *.exe and *.dll's but the *.pdb files so that the debug into is there and any exceptions will have exact line numbers for debugging purposes.

**Comment by I3Questor** [comment]
Like this?

Unhandled exception in application.
Outer Exception: System.ArgumentException: An item with the same key has already been added.

   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)

   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)

   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)

   at Questor.Storylines.Storyline..ctor() in d:\New Downloads\INNERSPACE\ISeeDEDPpl-Questor-0fe22fe -
Current\Questor\Storylines\Storyline.cs:line 37

   at Questor.Behaviors.CombatMissionsBehavior..ctor() in d:\New Downloads\INNERSPACE\ISeeDEDPpl-Questor-0fe22fe -
Current\Questor\Behaviors\CombatMissionsBehavior.cs:line 92

   at Questor.Questor..ctor(QuestorfrmMain form1) in d:\New Downloads\INNERSPACE\ISeeDEDPpl-Questor-0fe22fe -
Current\Questor\Questor.cs:line 57

   at Questor.QuestorfrmMain..ctor() in d:\New Downloads\INNERSPACE\ISeeDEDPpl-Questor-0fe22fe -
Current\Questor\QuestorUI.cs:line 39

   at Questor.Program.Main(String[] args) in d:\New Downloads\INNERSPACE\ISeeDEDPpl-Questor-0fe22fe -
Current\Questor\Program.cs:line 356

   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)

   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, Evidence assemblySecurity, String[] args)

   at System.AppDomain.ExecuteAssemblyByName(String assemblyName, Evidence assemblySecurity, String[] args)

   at LavishVMRuntime.LVMDomainManager.AsEx.NewExecuteAssembly4()

   at LavishVMRuntime.LVMDomainManager.AsEx.NewExecuteAssembly()

   at LavishVMRuntime.LVMDomainManager.AssemblyExecuter(Object Obj)

**Comment by ahaw** [comment]
This is the problem in storyline.cs around line 37:
_storylines = new Dictionary<string, IStoryline>{...}
probably duplicate entries.
                            {

**Comment by ISeeDEDPpl** [comment]
fixed
https://github.com/ISeeDEDPpl/Questor/commit/c2597d2ee7482ff82128f6c4d5ea3a42f7e47710

this would not likely keep questor docked however... so their may be a second issue that needs resolving.
