### ISSUE TITLE
QuestorManager drop funcion

### ISSUE THREAD

**Issue by sigmastk** [ISeeDEDPpl/Questor#205]
I am getting error when using questormanager drop feature. Is there any1 else experiencing similar problem ?

I am using 2 or 3 iseededppl forks ago (you update them superfast, I lost track :) ).

Console log :

Logging to gc:\innerspace.log
14:50:23 o[ yQuestorManager o] wStart
14:50:25 o[ yQuestorManager o] wDrop: Begin
14:50:26 o[ yDrop o] wOpening Hangar
14:50:27 o[ yDrop o] wOpening Cargo Hold
Exception during event execution: System.NotImplementedException: The method or operation is not implemented.
   at . . (Dictionary`2 , Object[] )
   at . . (  , Object[] )
   at DirectEve.DirectItem. (DirectEve ,   ,   )
   at DirectEve.DirectContainer.get_Items()
   at Questor.Modules.Actions.Drop.ProcessState() in \path\\Questor.Modules\Actions\Drop.cs:line 129
   at QuestorManager.QuestorManagerUI.OnFrame(Object sender, EventArgs e) in \path\\QuestorManager\QuestorManagerUI.cs:line 504
   at . . (DirectEve , Object , EventArgs )
   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)
   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)
Exception during event execution: System.NotImplementedException: The method or operation is not implemented.
   at . . (Dictionary`2 , Object[] )
   at . . (  , Object[] )
   at DirectEve.DirectItem. (DirectEve ,   ,   )
   at DirectEve.DirectContainer.get_Items()
   at Questor.Modules.Actions.Drop.ProcessState() in \path\Questor.Modules\Actions\Drop.cs:line 129
   at QuestorManager.QuestorManagerUI.OnFrame(Object sender, EventArgs e) in \path\QuestorManager\QuestorManagerUI.cs:line 504
   at . . (DirectEve , Object , EventArgs )
   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)
   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)
Exception during event execution: System.NotImplementedException: The method or operation is not implemented.
   at . . (Dictionary`2 , Object[] )
   at . . (  , Object[] )
   at DirectEve.DirectItem. (DirectEve ,   ,   )
   at DirectEve.DirectContainer.get_Items()
   at Questor.Modules.Actions.Drop.ProcessState() in \path\Questor.Modules\Actions\Drop.cs:line 129
   at QuestorManager.QuestorManagerUI.OnFrame(Object sender, EventArgs e) in \path\QuestorManager\QuestorManagerUI.cs:line 504
   at . . (DirectEve , Object , EventArgs )
   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)
   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

**Comment by ISeeDEDPpl** [comment]
if you update to latest and try this again (w logs) it is more likely to get fixed. 

in latest github line 129 is:
`
List<DirectItem> allItem = Cache.Instance.CargoHold.Items;
`
which should work fine if the cargohold is open... and it should be at that point. I am guessing that whatever rev you are using our line numbers are diff. update and repost the log please. OR tell me what github rev you are using so I can look at that github rev.

**Comment by ISeeDEDPpl** [comment]
this should be fixed. if not please reopen.
