### ISSUE TITLE
log off error

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#250]
time date... [Questor] Autostart is false: Stopping EVE with quit command (if EVE is going to restart it will do so
externally)
Exception during event execution: System.ArgumentOutOfRangeException: The added or subtracted value results in an
un-representable DateTime.

Parameter name: value

   at System.DateTime.AddTicks(Int64 value)

   at System.DateTime.Add(Double value, Int32 scale)

   at System.DateTime.AddSeconds(Double value)

   at Questor.Modules.BackgroundTasks.Cleanup.CloseQuestor() in c:\Program Files (x86)\InnerSpace.NET
Programs\Questor.Modules\BackgroundTasks\Cleanup.cs:line 304

   at Questor.Questor.OnFrame(Object sender, EventArgs e) in c:\Program Files (x86)\InnerSpace.NET
Programs\Questor\Questor.cs:line 612

   at ..(DirectEve , Object , EventArgs )

   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

http://pastebin.com/f9X55LaH

**Comment by ISeeDEDPpl** [comment]
https://github.com/ISeeDEDPpl/Questor/commit/2eeec4fd4a7b2b77a81240dbce40c3a93fc3237c
