### ISSUE TITLE
Bug with 9e4441d1

### ISSUE THREAD

**Issue by Pluckyduck** [ISeeDEDPpl/Questor#254]
*
*
Normal start off
*
*

XX:XX:36 [Questor] Schedule: setup correctly: stoptime is [7:00 PM]
XX:XX:36 [Questor] EVE instance: totalMegaBytesOfMemoryUsed - 616 MB
XX:XX:36 [Settings] Loading Settings from [C:\Program Files (x86)\InnerSpace.NET Programs\Super Sex.xml]
XX:XX:37 [Settings] MissionsPath is: [C:\Program Files (x86)\InnerSpace.NET Programs\T-Gurl]
XX:XX:37 [Settings] Loothangar [1st]
XX:XX:37 [Settings] AmmoHangar [1st]
XX:XX:37 [Settings] Found only one agent in your character XML: MultiAgentSupport is [False]
XX:XX:37 [Settings] Loading Mission Blacklist
XX:XX:37 [Settings]         Mission Blacklist now has [54] entries
XX:XX:37 [Settings] Loading Faction Blacklist
XX:XX:37 [Settings]         Missions from the faction [Caldari State] will be declined
XX:XX:37 [Settings]         Faction Blacklist now has [1] entries
XX:XX:37 [Cache.CurrentAgent] [ Miss Behaving ] AgentID [ 1 69 4 U]
XX:XX:37 [Logging] [ Miss Behaving ] AgentID [ 1 69 4 U]
XX:XX:39 [Questor] Checking: Current time [11/04/2012 14:30:39] StopTimeSpecified [True] StopTime [ 11/4/2012 7:00:00 PM] ManualStopTime = 11/4/2012 7:28:50 PM
XX:XX:39 [Questor] Start Mission Behavior
XX:XX:40 [CombatMissionsBehavior] Random start delay of [33] seconds
XX:XX:06 [Questor.RunOnce30SecAfterStartup] Running Innerspace command: WindowText EVE - Super Sex
XX:XX:06 [Questor.RunOnce30SecAfterStartup] Running Innerspace command: timedcommand 100 windowtaskbar on Super Sex
Tray icon enabled
XX:XX:30 [CombatMissionsBehavior.TravelHome] Destination: [Super station]
XX:XX:30 [TravelerDestination.StationDestination] Destination set to [Super station]
XX:XX:33 [TravelerDestination.StationDestination] Arrived in station
XX:XX:33 [CombatMissionsBehavior.TravelHome] Arrived at destination
XX:XX:34 [DroneStats] We do not use drones in this type of ship, skipping dronestats
XX:XX:34 [AgentInteraction] Start Conversation [Complete Mission]
XX:XX:44 [AgentInteraction] Replying to agent
XX:XX:47 [AgentInteraction] Saying [Complete Mission]
XX:XX:47 [AgentInteraction] Closing conversation
XX:XX:48 [AgentInteraction] This window indicates an error completing a mission: [1] errors already we will stop questor and halt restarting when we reach 3
XX:XX:53 [AgentInteraction] Attempting to close Agent Window
XX:XX:54 [AgentInteraction] Done
XX:XX:54 [CurrentCombatMissionBehavior.CompleteMission]Skipping statistics: We did not yet complete the mission
XX:XX:55 [CombatMissionsBehavior] UnloadLoot: Begin
XX:XX:05 [Unloadloot.MoveAmmo] Stacking Corporate Ammo Hangar
XX:XX:06 [UnloadLoot.MoveAmmo] Done Moving Ammo
XX:XX:08 [Cache.StackLootHangar] Stacking Corporate Loot Hangar: waiting [3sec]
XX:XX:12 [UnloadLoot.MoveLoot]Loot was worth an estimated [0] isk in buy-orders
XX:XX:12 [CombatMissionsBehavior.Unloadloot] We are on mission
XX:XX:13 [CombatMissionsBehavior] Random start delay of [35] seconds
XX:XX:38 [Storyline] Currently have  [0] available storyline missions
XX:XX:38 [Storyline] Currently have  [0] storyline missions questor knows how to do
XX:XX:38 [Storyline] Currently have  [0] storyline missions questor knows how to do and are not blacklisted
XX:XX:38 [AgentInteraction] Start conversation [Start Mission]
XX:XX:48 [AgentInteraction] Replying to agent
XX:XX:52 [AgentInteraction] Waiting for mission
XX:XX:57 [AgentInteraction] [Miss Behaving] standing toward me is [9.64], minAgentGreyListStandings: [7]
XX:XX:57 [AgentInteraction] Mission enemy faction: Gallente Federation
XX:XX:57 [AgentInteraction] mission bookmark info: [30002784]
XX:XX:57 [GetDungeonId] DungeonID is: localsvc:service=agents&method=PopupDungeonShipRestrictionList&agentID=3016847&charID=91291840&dungeonID=732
XX:XX:57 [Cache.SetmissionXmlPath] Unable to find faction specific [C:\Program Files (x86)\InnerSpace.NET Programs\T-Gurl\Enemies Abound (4 of 5)-Gallente Federation.xml] trying generic version
XX:XX:57 [AgentInteraction] Loading mission xml [Enemies Abound (4 of 5)] from [C:\Program Files (x86)\InnerSpace.NET Programs\T-Gurl\Enemies Abound (4 of 5).xml]
XX:XX:57 [AgentInteraction] Mission [Enemies Abound (4 of 5)] already accepted
XX:XX:57 [AgentInteraction] Closing conversation
XX:XX:03 [AgentInteraction] Attempting to close Agent Window
XX:XX:04 [AgentInteraction] Done
XX:XX:05 [Arm] Begin
XX:XX:06 [Arm] Activating combat ship
XX:XX:07 [Arm.ActivateCombatShip] Cargohold is closed
Exception during event execution: System.NullReferenceException: Object reference not set to an instance of an object.

   at Questor.Modules.Actions.Arm.ProcessState() in c:\Program Files (x86)\InnerSpace.NET Programs\Questor.Modules\Actions\Arm.cs:line 332

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in c:\Program Files (x86)\InnerSpace.NET Programs\Questor\Behaviors\CombatMissionsBehavior.cs:line 521

   at Questor.Questor.OnFrame(Object sender, EventArgs e) in c:\Program Files (x86)\InnerSpace.NET Programs\Questor\Questor.cs:line 553

   at ..(DirectEve , Object , EventArgs )

   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)
XX:XX:08 [Arm.ActivateCombatShip] Cargohold is closed
Exception during event execution: System.NullReferenceException: Object reference not set to an instance of an object.

   at Questor.Modules.Actions.Arm.ProcessState() in c:\Program Files (x86)\InnerSpace.NET Programs\Questor.Modules\Actions\Arm.cs:line 332

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in c:\Program Files (x86)\InnerSpace.NET Programs\Questor\Behaviors\CombatMissionsBehavior.cs:line 521

   at Questor.Questor.OnFrame(Object sender, EventArgs e) in c:\Program Files (x86)\InnerSpace.NET Programs\Questor\Questor.cs:line 553

   at ..(DirectEve , Object , EventArgs )

   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)
XX:XX:40 [Arm.ActivateCombatShip] Cargohold is closed
Exception during event execution: System.NullReferenceException: Object reference not set to an instance of an object.

   at Questor.Modules.Actions.Arm.ProcessState() in c:\Program Files (x86)\InnerSpace.NET Programs\Questor.Modules\Actions\Arm.cs:line 332

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in c:\Program Files (x86)\InnerSpace.NET Programs\Questor\Behaviors\CombatMissionsBehavior.cs:line 521

   at Questor.Questor.OnFrame(Object sender, EventArgs e) in c:\Program Files (x86)\InnerSpace.NET Programs\Questor\Questor.cs:line 553

   at ..(DirectEve , Object , EventArgs )

   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)
XX:XX:41 [Arm.ActivateCombatShip] Cargohold is closed
Exception during event execution: System.NullReferenceException: Object reference not set to an instance of an object.

   at Questor.Modules.Actions.Arm.ProcessState() in c:\Program Files (x86)\InnerSpace.NET Programs\Questor.Modules\Actions\Arm.cs:line 332

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in c:\Program Files (x86)\InnerSpace.NET Programs\Questor\Behaviors\CombatMissionsBehavior.cs:line 521

   at Questor.Questor.OnFrame(Object sender, EventArgs e) in c:\Program Files (x86)\InnerSpace.NET Programs\Questor\Questor.cs:line 553

   at ..(DirectEve , Object , EventArgs )

   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

*
*
At this point i manually open the cargohold.......................
*
*

XX:XX:43 [Arm.RepairShop [Drones]] Opening repairshop window
XX:XX:44 [Arm.RepairShop [Drones]] No drones available, nothing to repair.
XX:XX:40 [Questor] Wallet Balance Has Not Changed in [ 2 ] minutes.

just times out from this point

**Comment by ISeeDEDPpl** [comment]
can you verify that is still an issue?
