### ISSUE TITLE
Exception

### ISSUE THREAD

**Issue by EchuI** [ISeeDEDPpl/Questor#269]
When set "ExitWhenIdle" i get this error:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at ..( , String )
   at ..(DirectSession )
   at DirectEve.DirectSession.get_CharacterId()
   at DirectEve.DirectMe..ctor(DirectEve )
   at DirectEve.DirectEve.get_Me()
   at Questor.Modules.Logging.Statistics.WriteSessionLogClosing()
   at Questor.Modules.BackgroundTasks.Cleanup.CloseQuestor()
   at Questor.QuestorfrmMain.UpdateUiTick(Object sender, EventArgs e)
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)
```

**Comment by sigmastk** [comment]
I believe same issue is opened : https://github.com/ISeeDEDPpl/Questor/issues/272 .

**Comment by ISeeDEDPpl** [comment]
yes, duplicate issue, this one will be closed, the other issue will track progress.
