### ISSUE TITLE
Questor exception when querying wallet balance

### ISSUE THREAD

**Issue by yomon598** [ISeeDEDPpl/Questor#272]
Hello. Questor crashed several times today (I'm new to using it) with this unhandled exception:

System.NullReferenceException: Object reference not set to an instance of an object.
   at ..( , String )
   at ..(DirectSession )
   at DirectEve.DirectSession.get_CharacterId()
   at DirectEve.DirectMe..ctor(DirectEve )
   at DirectEve.DirectEve.get_Me()
   at Questor.Modules.Logging.Statistics.WriteSessionLogClosing() in C:\work\eve\q\Questor\Questor.Modules\Logging\Statistics.cs:line 359
   at Questor.Modules.BackgroundTasks.Cleanup.CloseQuestor() in C:\work\eve\q\Questor\Questor.Modules\BackgroundTasks\Cleanup.cs:line 57
   at Questor.QuestorfrmMain.UpdateUiTick(Object sender, EventArgs e) in C:\work\eve\q\Questor\Questor\QuestorUI.cs:line 588
   at System.Windows.Forms.Timer.OnTick(EventArgs e)
   at System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

In case there is more information that I can supply, please let me know.
Thanks in advance!

**Comment by ISeeDEDPpl** [comment]
`
<yomon> got this crash in questor several times today : http://pastie.org/5409208 , got any idea what causes it?
 dalikman has quit (Quit: http://www.mibbit.com ajax IRC Client)
<ISeeDEDPpl> odd: line += ((int)Cache.Instance.DirectEve.Me.Wealth + ";");        // WalletBalance
<ISeeDEDPpl>                 
<ISeeDEDPpl> strange that youd be getting an exception there
<CyberTechWork> wealth isn't initialized unless the wallet has been opened at least once
<CyberTechWork> unless you're starting the timer thread manually, ISeeDEDPpl, in DE, which is possible.
`

**Comment by sigmastk** [comment]
I have this same error. It happens to me when char wants to log off. I am using build of two days ago and schedules.xml for autlogon logoff

**Comment by ISeeDEDPpl** [comment]
the exception should now be avoided...
https://github.com/ISeeDEDPpl/Questor/commit/428284b79c27ef91b31fed3180b1526b8bbff041
