### ISSUE TITLE
Random crashes when starting a new mission

### ISSUE THREAD

**Issue by Blafasl** [ISeeDEDPpl/Questor#308]
After upgrading to the newest commit i get some weird crashes with questor across multiple VMs and even on the host computer itself.
It runs the mission perfect but crashes when it comes to get a new one, here is the console snippet from innerspace:

xx:xx:41 o[yCombatMissionsBehavioro] wUnloadLoot: Begin
xx:xx:42 o[yUnloadLoot.MoveAmmoo] wMoving [1] Ammo Stacks to AmmoHangar
xx:xx:43 o[yUnloadLoot.MoveAmmoo] wwill Continue in [ 2 ] sec
xx:xx:44 o[yUnloadLoot.MoveAmmoo] wwill Continue in [ 1 ] sec
xx:xx:46 o[yStackItemsHangarAsAmmoHangaro] ttest
xx:xx:46 o[yUnloadLoot.MoveAmmoo] wStacking Item Hangar
xx:xx:47 o[yUnloadLoot.MoveAmmoo] wDone Moving Ammo
xx:xx:47 o[yStackItemsHangarAsAmmoHangaro] ttest
xx:xx:48 o[yCache.StackLootHangaro] wStacking Item Hangar
xx:xx:49 o[yUnloadLoot.MoveLooto] tLoot was worth an estimated [0] isk in buy-orders
xx:xx:49 o[yCombatMissionsBehavior.Unloadlooto] wCharacterMode: [Combat Missions], AfterMissionSalvaging: [False], CombatMissionsBehaviorState: [Idle]
xx:xx:50 o[yQuestoro] wChecking: Current time [12/18/2012 xx:xx:50] StopTimeSpecified [True] StopTime [ 12/18/2012 xx:00:00 PM] ManualStopTime = 12/19/2012 5:35:56 AM
xx:xx:50 o[yQuestor.SkillQueueChecko] wTraining Queue is full. [29.07 is more than 24 hours]
xx:xx:51 o[yQuestoro] wStart Mission Behavior
xx:xx:52 o[yCombatMissionsBehavioro] wRandom start delay of [37] seconds
xx:xx:20 o[yQuestoro] wWallet Balance Has Not Changed in [ 2 ] minutes.
Exception during event execution: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

   at ..(IntPtr , IntPtr , IntPtr )

   at ..(Dictionary`2 , Object[] )

   at ..( , Object[] )

   at ..( , String , Object[] )

   at ..(Int64 , DirectEve )

   at DirectEve.DirectAgent.(DirectEve , String )

   at DirectEve.DirectEve.GetAgentByName(String agentName)

   at Questor.Modules.Caching.Cache.get_Agent() in c:\Users\Destiny\Desktop\questor\Questor\Questor.Modules\Caching\Cache.cs:line 1198

   at Questor.Behaviors.CombatMissionsBehavior.ValidateCombatMissionSettings() in c:\Users\Destiny\Desktop\questor\Questor\Questor\Behaviors\CombatMissionsBehavior.cs:line 143

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in c:\Users\Destiny\Desktop\questor\Questor\Questor\Behaviors\CombatMissionsBehavior.cs:line 391

   at Questor.Questor.OnFrame(Object sender, EventArgs e) in c:\Users\Destiny\Desktop\questor\Questor\Questor\Questor.cs:line 586

   at ..(DirectEve , Object , EventArgs )

   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

The exceptions comes uo seven times and the eve process crashes. Some points about it:
- It never crashes at the first mission
- The Agent is already in the Adressbook
- The cache was cleared and the RAM tested, no faults with memtest86
- The is no pattern for me to see what could be the next client that crashes, it seems completely random.

If you need me something to do to debug that thing, or a guess what could be wrong, i would be very happy to hear from it.

**Comment by ISeeDEDPpl** [comment]
this might resolve that issue: https://github.com/ISeeDEDPpl/Questor/commit/caa8a6cc27261c99e620b57a947094dce3ddd085

**Comment by Blafasl** [comment]
The update helped by a good margin. I did got another crash but i couldn't catch it right in time but its a whole lot better than a crash every 30 minutes or so.
And... one of my clients got a exception while stacking the item hangar:

19:02:43 o[yCache.StackLootHangaro] wStacking Item Hangar
Exception during event execution: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.

   at ..(IntPtr , String )

   at ..( , String )

   at DirectEve.DirectContainer.StackAll()

   at Questor.Modules.Caching.Cache.StackItemsHangarAsLootHangar(String module) in c:\Users\Destiny\Desktop\questor\Questor\Questor.Modules\Caching\Cache.cs:line 2825

   at Questor.Modules.Caching.Cache.StackLootHangar(String module) in c:\Users\Destiny\Desktop\questor\Questor\Questor.Modules\Caching\Cache.cs:line 4363

   at Questor.Modules.Actions.UnloadLoot.MoveLoot() in c:\Users\Destiny\Desktop\questor\Questor\Questor.Modules\Actions\UnloadLoot.cs:line 187

   at Questor.Modules.Actions.UnloadLoot.ProcessState() in c:\Users\Destiny\Desktop\questor\Questor\Questor.Modules\Actions\UnloadLoot.cs:line 436

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in c:\Users\Destiny\Desktop\questor\Questor\Questor\Behaviors\CombatMissionsBehavior.cs:line 888

   at Questor.Questor.OnFrame(Object sender, EventArgs e) in c:\Users\Destiny\Desktop\questor\Questor\Questor\Questor.cs:line 586

   at ..(DirectEve , Object , EventArgs )

   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

---

I hope that this is solvable.

**Comment by Blafasl** [comment]
Now that i got a little time to play around with the second error i found out that i help to manually set questor to do a new mission. The Access violation seems to solve itself after the missions and runs happily thereafter.

So a way to get around that would be that questor catches the exception and skips the stacking hangar action to do a new mission.

What do you think of it?

**Comment by ISeeDEDPpl** [comment]
yeah, but it would be even better to not have the exception in the first place. It seems like DE/EVE is pissed about us doing an action too quickly, but  I cant see where that is possible currently.

**Comment by ISeeDEDPpl** [comment]
https://github.com/ISeeDEDPpl/Questor/commit/0e0a22008a51f5607ecef51acbef8b02ac23670b
