### ISSUE TITLE
I've got an exception on [Materials for War Preparation]

### ISSUE THREAD

**Issue by AdditionalFrame** [ISeeDEDPpl/Questor#337]
So, questor got an exception. I'm using Feb 9th version (Commit hash:   0417ed08aeac2aaba59db4da8df30787ad5ed48c). Stack trace is below:

```
Exception during event execution: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)

   at Questor.Storylines.Storyline.IdleState() in d:\Projects\Questor\ISeeDEDPpl\Questor\Storylines\Storyline.cs:line 361

   at Questor.Storylines.Storyline.ProcessState() in d:\Projects\Questor\ISeeDEDPpl\Questor\Storylines\Storyline.cs:line 484

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in d:\Projects\Questor\ISeeDEDPpl\Questor\Behaviors\CombatMissionsBehavior.cs:line 1256

   at Questor.Questor.OnFrame(Object sender, EventArgs e) in d:\Projects\Questor\ISeeDEDPpl\Questor\Questor.cs:line 604

   at DirectEve.DirectEve.(Object , EventArgs )

   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)
Exception during event execution: System.NullReferenceException: Object reference not set to an instance of an object.

   at Questor.Storylines.Storyline.ProcessState() in d:\Projects\Questor\ISeeDEDPpl\Questor\Storylines\Storyline.cs:line 490

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in d:\Projects\Questor\ISeeDEDPpl\Questor\Behaviors\CombatMissionsBehavior.cs:line 1256

   at Questor.Questor.OnFrame(Object sender, EventArgs e) in d:\Projects\Questor\ISeeDEDPpl\Questor\Questor.cs:line 604

   at DirectEve.DirectEve.(Object , EventArgs )

   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)
```

**Comment by ISeeDEDPpl** [comment]
this should be fixed in current experimental.
