### ISSUE TITLE
Innerspace Exception Thrown on GoToBase - hangs and does not return to base

### ISSUE THREAD

**Issue by CasualBod** [ISeeDEDPpl/Questor#349]
Whatever you did with the .NET compile thing, probably broke the GoToBase action right after Questor completes a mission through <done> action or after salvaging, it fails to do anything after it goes normally through the missions etc. But then when it's time to return to base - Innerspace exceptions thrown. Here are some bits that i managed to copy-paste from console.

I am not a coding guru tbh, but what I can gather from these is that there are some hick-ups where questor situated in Innerspace.NET Programs\ tries to look for file references and paths from it's compile directory (the folder on desktop that i use to extract the latest build of questor, then I proceed on to use compile.bat and edit transfertolive.bat for absolute path, then run it to transfer. 

**\* Running compile.bat did not show any errors, just some warnings as usual. ***

Exception during event execution: System.NullReferenceException: Object reference not set to an instance 
   at Questor.Modules.Activities.Traveler.TravelToAgentsStation(String module) in
c:\Users\XXXXXXX\Desktop\XXXXXX\Questor\Questor-BleedingEdge\Questor.Modules\Activities\Traveler.cs:line 378

   at Questor.Modules.Activities.Traveler.TravelHome(String module) in
c:\Users\XXXXXXX\Desktop\XXXXXX\Questor\Questor-BleedingEdge\Questor.Modules\Activities\Traveler.cs:line 337

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in
c:\Users\XXXXXXX\Desktop\XXXXXX\Questor\Questor-BleedingEdge\Questor\Behaviors\CombatMissionsBehavior.cs:line
   at Questor.Questor.OnFrame(Object sender, EventArgs e) in c:\Users\XXXXXXX\Desktop\XXXXXX\Questor\Questor-BleedingEdge\Questor-
   at DirectEve.DirectEve.(Object , EventArgs )

   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)
Exception during event execution: System.NullReferenceException: Object reference not set to an instance 
   at Questor.Modules.Activities.Traveler.TravelToAgentsStation(String module) in
c:\Users\XXXXXXX\Desktop\XXXXXX\Questor\Questor-BleedingEdge\Questor.Modules\Activities\Traveler.cs:line 378

   at Questor.Modules.Activities.Traveler.TravelHome(String module) in
c:\Users\XXXXXXX\Desktop\XXXXXX\Questor\Questor-BleedingEdge\Questor.Modules\Activities\Traveler.cs:line 337

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in
c:\Users\XXXXXXX\Desktop\XXXXXX\Questor\Questor-BleedingEdge\Questor\Behaviors\CombatMissionsBehavior.cs:line
   at Questor.Questor.OnFrame(Object sender, EventArgs e) in c:\Users\XXXXXXX\Desktop\XXXXXX\Questor\Questor-BleedingEdge\Questor-
   at DirectEve.DirectEve.(Object , EventArgs )

   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)
Exception during event execution: System.NullReferenceException: Object reference not set to an instance 
   at Questor.Modules.Activities.Traveler.TravelToAgentsStation(String module) in
c:\Users\XXXXXXX\Desktop\XXXXXX\Questor\Questor-BleedingEdge\Questor.Modules\Activities\Traveler.cs:line 378

   at Questor.Modules.Activities.Traveler.TravelHome(String module) in
c:\Users\XXXXXXX\Desktop\XXXXXX\Questor\Questor-BleedingEdge\Questor.Modules\Activities\Traveler.cs:line 337

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in
c:\Users\XXXXXXX\Desktop\XXXXXX\Questor\Questor-BleedingEdge\Questor\Behaviors\CombatMissionsBehavior.cs:line
   at Questor.Questor.OnFrame(Object sender, EventArgs e) in c:\Users\XXXXXXX\Desktop\XXXXXX\Questor\Questor-BleedingEdge\Questor-
   at DirectEve.DirectEve.(Object , EventArgs )

   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)
Exception during event execution: System.NullReferenceException: Object reference not set to an instance 
   at Questor.Modules.Activities.Traveler.TravelToAgentsStation(String module) in
c:\Users\XXXXXXX\Desktop\XXXXXX\Questor\Questor-BleedingEdge\Questor.Modules\Activities\Traveler.cs:line 378

   at Questor.Modules.Activities.Traveler.TravelHome(String module) in
c:\Users\XXXXXXX\Desktop\XXXXXX\Questor\Questor-BleedingEdge\Questor.Modules\Activities\Traveler.cs:line 337

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in
c:\Users\XXXXXXX\Desktop\XXXXXX\Questor\Questor-BleedingEdge\Questor\Behaviors\CombatMissionsBehavior.cs:line
   at Questor.Questor.OnFrame(Object sender, EventArgs e) in c:\Users\XXXXXXX\Desktop\XXXXXX\Questor\Questor-BleedingEdge\Questor-
   at DirectEve.DirectEve.(Object , EventArgs )

   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

**Comment by ISeeDEDPpl** [comment]
fixed already: https://github.com/ISeeDEDPpl/Questor/commit/ecb4c38bc6c4e4996afb13ce6d48633264190cea
