### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by kn0xv1lle** [ISeeDEDPpl/Questor#357]
Getting this issue dont know if its just me or wrong settings.

 [Combat.ProcessState] Exception [System.NullReferenceException: Object reference not set to an instance of an object.
   at Questor.Modules.Caching.Cache.<GetBestTarget>b__e1(PriorityTarget pt) in
c:\Questor-BleedingEdge\Questor.Modules\Caching\Cache.cs:line 2791

   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)

   at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)

   at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)

   at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()

   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()

   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)

   at Questor.Modules.Caching.Cache.GetBestTarget(EntityCache currentTarget, Double distance, Boolean lowValueFirst, String
callingroutine) in c:\Questor-BleedingEdge\Questor.Modules\Caching\Cache.cs:line 2790

   at Questor.Modules.Combat.Combat.GetTarget() in c:\Questor-BleedingEdge\Questor.Modules\Combat\Combat.cs:line 416

**Comment by ISeeDEDPpl** [comment]
fixed in bleedingedge, thanks
