### ISSUE TITLE
Storyline problem

### ISSUE THREAD

**Issue by drokk99** [ISeeDEDPpl/Questor#370]
4fee182bcc091c31e892aa9fb69acbc2a67c0982   Still throwing this exception when trying to do a storyline, happens right after it sets the destination to the agent. The mission was Fire and Ice if that makes any difference.

Exception during event execution: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.

   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)

   at Questor.Modules.Caching.Cache.CheckifRouteIsAllHighSec() in c:\Users\54545454\Desktop\Questor-experimental\Questor.Modules\Caching\Cache.cs:line 2595

   at Questor.Storylines.Storyline.GotoAgent(StorylineState nextState) in c:\Users\54545454\Desktop\Questor-experimental\Questor\Storylines\Storyline.cs:line 406

   at Questor.Storylines.Storyline.ProcessState() in c:\Users\54545454\Desktop\Questor-experimental\Questor\Storylines\Storyline.cs:line 513

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in c:\Users\54545454\Desktop\Questor-experimental\Questor\Behaviors\CombatMissionsBehavior.cs:line 1307
   at Questor.Questor.OnFrame(Object sender, EventArgs e) in c:\Users\54545454\Desktop\Questor-experimental\Questor\Questor.cs:line 631

   at ..(DirectEve , Object , EventArgs )

   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

**Comment by ISeeDEDPpl** [comment]
the exception and its line numbers do not match the revision you linked. You must have been running an older (broken) rev.

`at Questor.Modules.Caching.Cache.CheckifRouteIsAllHighSec() in c:\Users\54545454\Desktop\Questor-experimental\Questor.Modules\Caching\Cache.cs:line 2595`

is: 
`public DirectItem CheckCargoForItem(int typeIdToFind, int quantityToFind)
        {
            DirectContainer cargo = Cache.Instance.DirectEve.GetShipsCargo();
            DirectItem item = cargo.Items.FirstOrDefault(i => i.TypeId == typeIdToFind && i.Quantity >= quantityToFind);
            return item;
        }`
in that github rev you linked. (which I made more robust, but that has NOTHING to do with this log =)
Either I need to know what github rev this actually was (so I can match line numbers and figure out what is still broken) or you will need to reproduce this log with latest github (please)

**Comment by drokk99** [comment]
hmmm.. ok, sorry I must have been half asleep when I tested that... I just downloaded the latest bleeding edge and storylines seem to be working fine, might as well close this, I will reopen if any probs after testing a few more.
