### ISSUE TITLE
Traveler problem

### ISSUE THREAD

**Issue by botina** [ISeeDEDPpl/Questor#490]
Treveler dont want to dock in station:

20:21:03 [QuestorManager] Exception, [System.NullReferenceException: Object reference not set to an instance of an
object.

 at Questor.Modules.Caching.Cache.<get_ClosestStargate>b__6e(EntityCache s) in c:.....\Questor-BleedingEdge\Questor.Modules\Caching\Cache.cs:line 2051

 at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)

 at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)

 at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()

 at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)

 at Questor.Modules.Caching.Cache.get_ClosestStargate() in c:.....\Questor-BleedingEdge\Questor.Modules\Caching\Cache.cs:line 2051

 at Questor.Modules.Actions.TravelerDestination.useInstaBookmark() in c:....\Questor-BleedingEdge\Questor.Modules\Actions\TravelerDestination.cs:lin
e 70

 at Questor.Modules.Actions.StationDestination.PerformFinalDestinationTask(Int64 stationId, String stationName) in
c:.......\Questor-BleedingEdge\Questor.Modules\Actions\TravelerDestination.cs:lin
e 210

 at Questor.Modules.Actions.StationDestination.PerformFinalDestinationTask() in c:.......\Questor-BleedingEdge\Questor.Modules\Actions\TravelerDestination.cs:lin
e 174

 at Questor.Modules.Activities.Traveler.ProcessState() in c:.......\Questor-BleedingEdge\Questor.Modules\Activities\Traveler.cs:line 670

 at QuestorManager.QuestorManagerUI.OnFrame(Object sender, EventArgs e) in c:......\Questor-BleedingEdge\QuestorManager\QuestorManagerUI.cs:line 663]

AND on second eve client on same PC questor dont want even to start treveling:

10:09:21 [QuestorManager] Exception, [System.ArgumentNullException: Value cannot be null.

Parameter name: source

   at System.Linq.Enumerable.All[TSource](IEnumerable`1 source, Func`2 predicate)

   at QuestorManager.QuestorManagerUI.InitializeTraveler() in c:.......\64d71a4a78425779518e69c72b8be02574539b21\Questor-BleedingEdge\QuestorManager\QuestorManagerUI.cs:line 207

   at QuestorManager.QuestorManagerUI.OnFrame(Object sender, EventArgs e) in c:........\64d71a4a78425779518e69c72b8be02574539b21\Questor-BleedingEdge\QuestorManager\QuestorManagerUI.cs:line 306]

**Comment by ISeeDEDPpl** [comment]
fixed.
