### ISSUE TITLE
Null reference during SWITCH state.

### ISSUE THREAD

**Issue by CasualBod** [ISeeDEDPpl/Questor#496]
XX:55:15 [Switch] Begin
XX:55:16 [SwitchShip] Opening Ship Hangar: waiting [4sec]
XX:55:20 [SwitchShip] Activating combat ship
XX:55:21 [SwitchShip] Making [*******] active
XX:55:21 [SwitchShip] Activated
Exception during event execution: System.NullReferenceException: Object reference not set to an instance of an object.

   at Questor.Modules.Actions.SwitchShip.ProcessState() in c:\Users\User\Desktop\Questor-BleedingEdge\Questor.Modules\Actions\SwitchShip.cs:line 57

   at Questor.Behaviors.CombatMissionsBehavior.ProcessState() in c:\Users\User\Desktop\Questor-BleedingEdge\Questor\Behaviors\CombatMissionsBehavior.cs:line
512

   at Questor.Questor.EVEOnFrame(Object sender, EventArgs e) in c:\Users\User\Desktop\Questor-BleedingEdge\Questor\Questor.cs:line 658

   at DirectEve.DirectEve.(Object , EventArgs )

   at DirectEve.InnerSpaceFramework.FrameHook(Object sender, EventArgs e)

   at LavishScriptAPI.LavishScript.Events.Event.Target(Int32 argc, UInt32 argvToken, Int32 ThisObject)

**Comment by ISeeDEDPpl** [comment]
fixed in bleedingedge: https://github.com/ISeeDEDPpl/Questor/commit/4f08cc74ec30e18ecf37a6d9713552dc1c0badec
