### ISSUE TITLE
 Exception in ActivateWeapons()

### ISSUE THREAD

**Issue by ghost** [ISeeDEDPpl/Questor#523]
I've used Questor extensively in the past without issues, but since reinstalling it this morning I'm unable to attack NPCs. I have no issues moving within combat range, but once there the log spams the following error:

21:33:59 [Combat.ProcessState] Exception [System.InvalidOperationException: Sequence contains no elements
at System.Linq.Enumerable.Max(IEnumerable`1 source)
at System.Linq.Enumerable.Max[TSource](IEnumerable`1 source, Func`2 selector)
at Questor.Modules.Combat.Combat.ActivateWeapons(EntityCache target) in d:\Dropbox\dev\eve\Questor\Questor.Modules\Combat\Combat.cs:line 630
at Questor.Modules.Combat.Combat.ProcessState() in d:\Dropbox\dev\eve\Questor\Questor.Modules\Combat\Combat.cs:line 2029]

I've looked through the code a bit and it seems to be choking on the following line:

MaxCharges = Math.Max(MaxCharges, weapons.Max(l => l.MaxCharges));

It could easily be related to a setup issue as I haven't setup a missile boat in quite awhile. I'm using 4 light missile launchers with scourge light missiles on a Caracal for L2 missions.

**Comment by ghost** [comment]
Sorted this out, I had an incorrect weapongroupid

**Comment by Pluckyduck** [comment]
@yomon the one that had the link to save the day.
