### ISSUE TITLE
just an exception

### ISSUE THREAD

**Issue by yomon598** [ISeeDEDPpl/Questor#526]
I'm a couple of commits behind, but shouldn't matter, line 2302 should be the current 2304.I had a quick look, dunno why this was null, maybe you can figure it out faster, here's the redacted log:

```
02:01:32 [Combat] Targeting primary weapon priority target [Coreli Patroller][[MaskedID]0740][2k away]
02:01:33 [Combat] Activating weapon [1] on [Corelior Trooper][[MaskedID]0714][2k away]
02:01:35 [Combat] Activating weapon [3] on [Corelior Trooper][[MaskedID]0714][2k away]
02:01:35 [Combat] Activating weapon [4] on [Corelior Trooper][[MaskedID]0714][2k away]
02:01:37 [Combat] Activating weapon [5] on [Corelior Trooper][[MaskedID]0714][2k away]
02:01:38 [EntityCache.LockTarget] [TargetCombatants.PrimaryWeaponPriorityEntity] tried to lock [Coreli Watchman][1.97k][[MaskedID]0741][2] targets already, we only have [2] slots!
02:01:40 [Panic] Start panicking, shield [39%] below [40%] S[39%] A[100%] C[35%]
02:01:40 [EntityCache.LockTarget] [TargetCombatants.PrimaryWeaponPriorityEntity] tried to lock [Coreli Watchman][1.97k][[MaskedID]0741][2] targets already, we only have [2] slots!
02:01:41 [Panic] Warping to [Station][6.91 AU away]
02:01:41 [Combat] Activating weapon [2] on [Corelior Trooper][[MaskedID]0714][2k away]
02:01:42 [Panic] Warping will be attempted again after [9sec]
02:01:42 [EntityCache.LockTarget] [TargetCombatants.PrimaryWeaponPriorityEntity] tried to lock [Coreli Watchman][1.97k][[MaskedID]0741][2] targets already, we only have [2] slots!
02:02:12 [Panic] We have warped off: My ShipType: [Ship] My ShipName [Ship]
02:02:12 [Panic] Docking with [Station][0 AU away]
02:02:17 [Panic] Entered a station, lower panic mode
02:02:18 [Panic] We're in a station, resume mission
02:02:19 [CombatMissionsBehavior] Setting Destination to 1st bookmark from AgentID: Agent007 with [Encounter] in the title
02:02:19 [TravelerDestination.MissionBookmarkDestination] Destination set to mission bookmark [Encounter (Deadspace) - System]
02:03:00 [TravelerDestination.SolarSystemDestination] Exiting station
02:03:19 [TravelerDestination.BookmarkDestination] Warping to bookmark [Encounter (Deadspace) - System][6.91 AU away]
02:03:29 [Questor.WalletCheck] Wallet Balance Has Not Changed in [ 2 ] minutes.
02:03:53 [PrimaryWeaponPriorityTargets] Remove Target that is no longer in the Entities list [Coreli Watchman]ID[[MaskedID]0741] PriorityLevel [Dampening]
02:03:53 [Cache.PrimaryWeaponPriorityEntities] Exception [System.NullReferenceException: Object reference not set to an instance of an object.
 at Questor.Modules.Caching.Cache.<get_PrimaryWeaponPriorityEntities>b__89(PriorityTarget pt) in C:\work\eve\gitstuff\questor\Questor\Questor.Modules\Caching\Cache.cs:line 2302
 at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
 at System.Linq.EnumerableSorter`2.ComputeKeys(TElement[] elements, Int32 count)
 at System.Linq.EnumerableSorter`1.Sort(TElement[] elements, Int32 count)
 at System.Linq.OrderedEnumerable`1.<GetEnumerator>d__0.MoveNext()
 at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
 at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
 at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
 at Questor.Modules.Caching.Cache.get_PrimaryWeaponPriorityEntities() in C:\work\eve\gitstuff\questor\Questor\Questor.Modules\Caching\Cache.cs:line 2302]
02:03:54 [TravelerDestination.BookmarkDestination] Arrived at the bookmark [Encounter (Deadspace) - System]
02:03:55 [PrimaryWeaponPriorityTargets] Remove Target that is no longer in the Entities list [Coreli Patroller]ID[[MaskedID]0740] PriorityLevel [Dampening]

```

**Comment by ISeeDEDPpl** [comment]
this should be fixed in bleedingedge, we ignore this nullref cleanly now.
