### ISSUE TITLE
Compile and execution problems

### ISSUE THREAD

**Issue by tetrikx** [ISeeDEDPpl/Questor#96]
When compiling latest build with directeve v1.328.4529.31250 (latest available on support site), I get a buylp error (which can be solved if you delete   </PropertyGroup> on line 33 of buylp.csproj) and 2 errors in valuedump.

Then, when executing the build, I get the error

Unhandled exception in application.
Outer Exception: System.TypeInitializationException: The type initializer for 'DirectEve.DirectEve' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
at DirectEve.DirectEve..cctor()
--- End of inner exception stack trace ---
at DirectEve.DirectEve..ctor()
at Questor.Program.Main(String[] args) in c:\Questor\Program.cs:line 288
at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
at System.AppDomain.ExecuteAssemblyByName(String assemblyName, Evidence assemblySecurity, String[] args)
at System.AppDomain.ExecuteAssemblyByName(String assemblyName, Evidence assemblySecurity, String[] args)
at LavishVMRuntime.LVMDomainManager.AsEx.NewExecuteAssembly2()
at LavishVMRuntime.LVMDomainManager.AsEx.NewExecuteAssembly()
at LavishVMRuntime.LVMDomainManager.AssemblyExecuter(Object Obj)
Inner Exception[1]: System.NullReferenceException: Object reference not set to an instance of an object.
at DirectEve.DirectEve..cctor()

in innerspace which might be because of different directeve versions used. (line 288 has the code _directEve = new DirectEve();)

So could you please upload on github also the latest directeve version that you are using?

Thanks

**Comment by ISeeDEDPpl** [comment]
isnt this the same error you were getting with questor? I dont think this is a generic error... anyone else seeing this?

**Comment by tetrikx** [comment]
I reinstalled the os and the issue dissapeared...probably it happened because of some stupid software I installed at some point...

Closing the issue with the remark that if you encounter the error, the fastest way to resolve it is to reinstall the os.
